# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bloodType',
            new_name='blood_type',
        ),
    ]
