# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_donor_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
