# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_patient_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='lastAttendance',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
