# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20170528_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'pictures'),
            preserve_default=False,
        ),
    ]
