# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_donor_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='picture',
        ),
        migrations.AddField(
            model_name='donor',
            name='docfile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
