# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20170619_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='availability',
            new_name='createdDate',
        ),
    ]
