# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20170619_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='availability',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
