# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20170617_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='docfile',
        ),
    ]
