# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_donor_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='availability',
        ),
    ]
