# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_remove_donor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
